# Generated by Django 5.1.7 on 2025-04-08 09:55

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garage',
            name='owner_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garage',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('oil_change', 'Oil Change'), ('tire_repair', 'Tire Repair'), ('engine_diagnostics', 'Engine Diagnostics'), ('brake_service', 'Brake Service'), ('battery_check', 'Battery Check')], max_length=69),
        ),
    ]
