# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_alter_garage_email_alter_garage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='garage',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='garage',
            name='services',
            field=models.TextField(help_text='List the services offered, separated by commas'),
        ),
    ]
