# Generated by Django 5.1.7 on 2025-04-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_alter_garage_email_alter_garage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='garage',
            name='services',
        ),
        migrations.AlterField(
            model_name='garage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.garagelocation'),
        ),
        migrations.AddField(
            model_name='garage',
            name='services',
            field=models.ManyToManyField(to='autocare.garageservice'),
        ),
    ]
